### PR TITLE
CBS-566 - Products using identity v1.1 API need to migrate to v2.0 

### PR DESCRIPTION
**Pull request by saumyaSgupta**
JIRA url: https://jira.rax.io/browse/CBS-566
changes done were removing dependency on Idenityv1.1 , adding default url for keystone middleware.

### CODE REVIEW

**Comment by cbs-cicd** [comment]
Added link-backs to the following issues:

* jira
  * https://jira.rax.io/browse/CBS-566

**Comment by cbs-cicd** [comment]
Triggering unit tests...

{{{test:queued:926}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/9/consoleFull

{{{test:started:9}}}

**Comment by cbs-cicd** [comment]
Test suite passed!

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/9/consoleFull

{{{test:complete}}}

**Comment by SaumyaRackspace** [comment]
With the previous findings we thought of adding default auth_url to lunrdriver/lunr/flags.py , but in recent investigations it has been found that registering keystone_authtoken.auth_url is not required and this part itself  should be removed . This change(hack) was done by Cory to tackle auth_url required by quota , but cinder has fixed this with commit 399d4c797bdd0b4930a01b435ea128cfad2fb388. Hence after upgrade to liberty-eol this code change (registering of keystone_authtoken.auth_url in flags.py) is not required now

**Pull request closed without merging**
