### PR TITLE
JIRA:CBS-235- requirement file is missing for lunrdriver

### PR DESCRIPTION
**Pull request by SaumyaRackspace**
Adding missing test-requirement.txt for lunrdriver , since lunrdriver basically extends cinder.VolumeAPI and cinder.VolumeDriver , adding requirements from cinder-liberty .

Jira Url- https://jira.rax.io/browse/CBS-235

### CODE REVIEW

**Comment by SaumyaRackspace** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://10.127.1.169:8080/jenkins/job/process_github_pr_lunrdriver/22/consoleFull

**Comment by SaumyaRackspace** [comment]
Could not find the following issues:

* jira
  * JIRA:CBS-235

**Comment by SaumyaRackspace** [comment]
Triggering unit tests...

{{{test:queued:78}}}

**Comment by SaumyaRackspace** [comment]
Running tests with './.unittests'...

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/24/consoleFull

{{{test:started:24}}}

**Comment by SaumyaRackspace** [comment]
Test suite passed!

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/24/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/apps/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/apps/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: http://10.127.1.169:8080/jenkins/job/test-lunrdriver-change/28/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
@corystone Requesting to review this change. Adding to the background to this , there were no automated unit testing existing for lunrdriver. Without existence of proper requirements file unittest suite couldn't be kicked off.

**Comment by cbs-cicd** [comment]
Triggering unit tests...

{{{test:queued:12708}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/1/consoleFull

{{{test:started:1}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/1/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/2/consoleFull

{{{test:started:2}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/2/consoleFull

{{{test:complete}}}

**Comment by SaumyaRackspace** [comment]
@here please ignore the current error seen here .. I have configured unit test job on http://jarvis.cbs.racklabs.com:8080 now (which re-picked this PR as it is still open) , where I'm facing some env issues.

**Pull request merged**
