### PR TITLE
Issue-26_Storage_node_space_allocation

### PR DESCRIPTION
**Pull request by SaumyaRackspace**
The change intends to stop volume creation from source if any case it has either snapshot or cloning operation in progress.Related JIRA ticket is CBS-617 .

### CODE REVIEW

**Comment by dwith** [comment]
Changes look good to me.

**Comment by cbs-cicd** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/process_github_pr_lunrdriver/6/consoleFull

**Comment by cbs-cicd** [comment]
Triggering unit tests...

{{{test:queued:3331}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunrdriver-change/11/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/12/consoleFull

{{{test:started:12}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/12/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/13/consoleFull

{{{test:started:13}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/13/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/14/consoleFull

{{{test:started:14}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/16/consoleFull

{{{test:started:16}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/16/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/17/consoleFull

{{{test:started:17}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/17/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: https://jarvis.cbs.racklabs.com/job/process_github_pr_lunrdriver/7/consoleFull

**Comment by cbs-cicd** [comment]
Failed to trigger unit tests: Error in request.Possibly authentication failed [403]

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/18/consoleFull

{{{test:started:18}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/18/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: https://jarvis.cbs.racklabs.com/job/process_github_pr_lunrdriver/8/consoleFull

**Comment by cbs-cicd** [comment]
Failed to trigger unit tests: Error in request.Possibly authentication failed [401]

**Comment by cbs-cicd** [comment]
Bug tracker issue check failed: No existing tracker issues found in any commit message

For more details, see: https://jarvis.cbs.racklabs.com/job/process_github_pr_lunrdriver/9/consoleFull

**Comment by cbs-cicd** [comment]
Failed to trigger unit tests: Error in request.Possibly authentication failed [401]

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/19/consoleFull

{{{test:started:19}}}

**Comment by cbs-cicd** [comment]
Failed to set up virtual environment: '/var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/python /var/lib/jenkins/workspace/test-lunrdriver-change/virtualenv/bin/pip install --skip-requirements-regex (?<![a-zA-Z0-9._-])(eventlet|python-glanceclient|python-keystoneclient|python-novaclient)(?![a-zA-Z0-9._-]) -r test-requirements.txt -i https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple' failed with return code 1

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/19/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/20/consoleFull

{{{test:started:20}}}

**Comment by cbs-cicd** [comment]
Test suite passed!

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/20/consoleFull

{{{test:complete}}}

**Comment by cbs-cicd** [comment]
Test suite passed!

For more details, see: https://jarvis.cbs.racklabs.com/job/test-lunrdriver-change/21/consoleFull

{{{test:complete}}}

**Pull request merged**
